spring:
  application:
    name: watch-wise-api
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/watchwise}
    username: ${SPRING_DATASOURCE_USERNAME:watchwise}
    password: ${SPRING_DATASOURCE_PASSWORD:watchwise}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
  flyway:
    enabled: true
    baseline-on-migrate: true

trakt:
  api:
    base-url: https://api.trakt.tv
    client-id: changeme
jwt:
  secret: changemechangemechangemechangeme
  expiration-seconds: 3600
